# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TM8S(object):
    def setupUi(self, TM8S):
        TM8S.setObjectName("TM8S")
        TM8S.resize(475, 550)
        TM8S.setMinimumSize(QtCore.QSize(475, 550))
        TM8S.setMaximumSize(QtCore.QSize(475, 550))
        palette = QtGui.QPalette()
        text_brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))  # Black text
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, text_brush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, text_brush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text,
                         QtGui.QBrush(QtGui.QColor(120, 120, 120)))  # Gray for disabled

        bg_brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, bg_brush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, bg_brush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base,
                         QtGui.QBrush(QtGui.QColor(240, 240, 240)))
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, text_brush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, text_brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 226))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 226))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 226))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(225, 225, 226))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        TM8S.setPalette(palette)
        self.group_box_player_search = QtWidgets.QGroupBox(parent=TM8S)
        self.group_box_player_search.setGeometry(QtCore.QRect(10, 0, 450, 200))
        self.group_box_player_search.setMinimumSize(QtCore.QSize(450, 200))
        self.group_box_player_search.setMaximumSize(QtCore.QSize(450, 200))
        self.group_box_player_search.setObjectName("group_box_player_search")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.group_box_player_search)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 590, 76))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 200, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.p1_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.p1_label.setObjectName("p1_label")
        self.gridLayout.addWidget(self.p1_label, 0, 0, 1, 1)
        self.p2_search_box = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.p2_search_box.setAutoFillBackground(False)
        self.p2_search_box.setEditable(True)
        self.p2_search_box.setObjectName("p2_search_box")
        self.gridLayout.addWidget(self.p2_search_box, 1, 1, 1, 1)
        self.p2_label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.p2_label.setObjectName("p2_label")
        self.gridLayout.addWidget(self.p2_label, 1, 0, 1, 1)
        self.p1_search_box = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.p1_search_box.setMinimumSize(QtCore.QSize(300, 0))
        self.p1_search_box.setEditable(True)
        self.p1_search_box.setObjectName("p1_search_box")
        self.gridLayout.addWidget(self.p1_search_box, 0, 1, 1, 1)
        self.player_search_button = QtWidgets.QPushButton(parent=self.group_box_player_search)
        self.player_search_button.setEnabled(False)
        self.player_search_button.setGeometry(QtCore.QRect(130, 120, 251, 28))
        self.player_search_button.setMaximumSize(QtCore.QSize(300, 150))
        self.player_search_button.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate)
        self.player_search_button.setFlat(False)
        self.player_search_button.setObjectName("player_search_button")

        # I googled how to manually set styles using QtDesigner code
        self.player_search_button.setStyleSheet("""
            QPushButton {
                background-color: #0078d7;
                color: white;
                border: none;
                border-radius: 3px;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #106ebe;
                color: white;
            }
            QPushButton:pressed {
                background-color: #005a9e;
                color: white;
            }
            QPushButton:disabled {
                background-color: #cccccc;
                color: #666666;
            }
        """)
        self.search_progress_bar = QtWidgets.QProgressBar(parent=self.group_box_player_search)
        self.search_progress_bar.setEnabled(False)
        self.search_progress_bar.setGeometry(QtCore.QRect(130, 160, 251, 21))
        self.search_progress_bar.setProperty("value", 24)
        self.search_progress_bar.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.search_progress_bar.setObjectName("search_progress_bar")
        self.reset_button = QtWidgets.QPushButton(parent=self.group_box_player_search)
        self.reset_button.setEnabled(True)
        self.reset_button.setGeometry(QtCore.QRect(10, 170, 75, 24))
        self.reset_button.setMaximumSize(QtCore.QSize(300, 150))
        self.reset_button.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName("reset_button")

        # I googled how to manually set styles using QtDesigner code
        self.reset_button.setStyleSheet("""     
            QPushButton {
                background-color: #cccccc;
                color: black;
                border: 1;
                border-radius: 3px;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: grey;
                color: red;
            }
            QPushButton:pressed {
                background-color: #005a9e;
                color: red;
            }
            QPushButton:disabled {
                background-color: #cccccc;
                color: #666666;
            }
        """)
        self.group_box_results = QtWidgets.QGroupBox(parent=TM8S)
        self.group_box_results.setGeometry(QtCore.QRect(9, 219, 461, 321))
        self.group_box_results.setObjectName("group_box_results")
        self.results_display = QtWidgets.QTextEdit(parent=self.group_box_results)
        self.results_display.setGeometry(QtCore.QRect(5, 21, 451, 291))
        self.results_display.setReadOnly(True)
        self.results_display.setObjectName("results_display")
        self.results_box_slider = QtWidgets.QSlider(parent=self.group_box_results)
        self.results_box_slider.setGeometry(QtCore.QRect(430, 30, 22, 271))
        self.results_box_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.results_box_slider.setObjectName("results_box_slider")

        self.retranslateUi(TM8S)
        QtCore.QMetaObject.connectSlotsByName(TM8S)
        TM8S.setTabOrder(self.p1_search_box, self.p2_search_box)
        TM8S.setTabOrder(self.p2_search_box, self.results_display)

    def retranslateUi(self, TM8S):
        _translate = QtCore.QCoreApplication.translate
        TM8S.setWindowTitle(_translate("TM8S", "Dialog"))
        self.group_box_player_search.setTitle(_translate("TM8S", "Player Search"))
        self.p1_label.setText(_translate("TM8S", "Player 1         "))
        self.p2_search_box.setCurrentText(_translate("TM8S", "Begin typing a player name"))
        self.p2_label.setText(_translate("TM8S", "Player 2"))
        self.p1_search_box.setCurrentText(_translate("TM8S", "Begin typing a player name"))
        self.player_search_button.setText(_translate("TM8S", "Search"))
        self.reset_button.setText(_translate("TM8S", "Reset"))
        self.group_box_results.setTitle(_translate("TM8S", "Results"))
        self.results_display.setHtml(_translate("TM8S", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TM8S = QtWidgets.QDialog()
    ui = Ui_TM8S()
    ui.setupUi(TM8S)
    TM8S.show()
    sys.exit(app.exec())
